[phases.setup]
nixPkgs = ["python311", "postgresql_16.dev", "gcc"]

[phases.install]
cmds = [
    "python -m venv --copies /opt/venv",
    ". /opt/venv/bin/activate && pip install --upgrade pip setuptools wheel",
    ". /opt/venv/bin/activate && pip install -r requirements.txt"
]

[phases.build]
cmds = [
    ". /opt/venv/bin/activate && python migrate.py upgrade"
]

[start]
cmd = ". /opt/venv/bin/activate && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
